name: Windows-RDP
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Hazirlik
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
          .\ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      - name: RDP ve Kullanici
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin Sifre123456! /add
          net localgroup administrators runneradmin /add
      - name: Baglan
        run: |
          Start-Process -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389"
          Start-Sleep -Seconds 15
          $response = Invoke-RestMethod -Uri http://localhost:4040/api/tunnels
          $url = $response.tunnels[0].public_url
          echo "===================================="
          echo "ADRES: $url"
          echo "KULLANICI: runneradmin"
          echo "SIFRE: Sifre123456!"
          echo "===================================="
          Start-Sleep -Seconds 21600
          
